### ISSUE TITLE
[Feature] Upper and lower case results

### ISSUE THREAD

**Issue by simsong** [jessek/hashdeep#178]
Converted from [SourceForge issue 913471](http://sourceforge.net/support/tracker.php?aid=913471), submitted by jessekornblum

md5deep should be able produce hashes with uppercase or
lowercase letters. For example:

md5deep current output
89385d08854f9906e094c1b262eaf5ec

Some other application's output
89385D08854F9906E094C1B262EAF5EC

The goal would be to allow interoperability with hashes
from other applications.

**Comment by Doryforos** [comment]
Consider the following scenario:

I have some files that are, for one reason or another, important to me, hence I keep them well from being lost or corrupted and, as a bonus, I am using their hashes as -- rather acceptably strong -- passwords for compressed files encryption, website credentials, etc.

Since passwords are case sensitive, I may use various combinations of upper or lowercase [portions of] these hashes for this purpose.

It would be useful, therefore, if the *deep executables were able to output hashes in uppercase as well -- since there is no easy way provided by MS-WINDOS to convert a character string to uppercase [see: Convert strings to upper or lower case @ http://www.robvanderwoude.com/battech_convertcase.php, for a very out-of-this-world-for-the-average-user example].

Kindly consider this suggestion: provide uppercase output as an option, while keeping the default output as is, in lowercase.
