### ISSUE TITLE
How to run hashdeep as a background, low priority (Windows) process ?

### ISSUE THREAD

**Issue by marbx** [jessek/hashdeep#374]
Using hashdeep version 4.4 on Windows 7.

With `hashdeep64.exe -r MYDIR`, Resource Monitor is showing 100% disk use, and the system is noticeably slowed.

What are the best options to keep hashdeep low priority?

With `hashdeep64.exe -r -p4096 -j1 MYDIR` Resource Monitor still shows 100% disk use, although the system remains responsive.

Thank you

**Comment by markuskramerIgitt** [comment]
I just notice that  `-p 4096` calculates, writes and compares a hash for every piece of 4096 bytes.

**Comment by simsong** [comment]
If the system is responsive, why do you care that resource use is 100%

**Comment by markuskramerIgitt** [comment]
Because 
The system could become unresponsive by a usage I have not tried and 
I would like to audit daily without that a user noticed disk activity. 
For me it does not matter how long audit takes.

**Comment by simsong** [comment]
If it doesn't matter how Long the audit takes, then simply do it run the program!  Clearly you care how long it takes---you want it to take less than 24 hours!

Windows is a modern operating system and can prioritize tasks. You can use the operating system features to manage resource allocation; you do not need for it to be implemented in user level!

>

**Comment by markuskramerIgitt** [comment]
From Microsoft, I only found "Windows System Resource Manager", which has
been deprecated with Windows server 2012 and not replaced.

Setting a lower reading priority from OS level seems to require third party
tools like
   https://sourceforge.net/projects/iopriority/ (declared as alpha)
from a discussion here
https://superuser.com/questions/136021/how-to-change-i-o-priority-of-a-process-or-thread-in-win7

For the time being, I will use hashdeep -j 1.

**Comment by simsong** [comment]
You can set the priority with the task manager.

http://www.askvg.com/how-to-permanently-set-process-priority-in-windows-task-manager/ <http://www.askvg.com/how-to-permanently-set-process-priority-in-windows-task-manager/>

http://www.wikihow.com/Change-Process-Priorities-in-Windows-Task-Manager <http://www.wikihow.com/Change-Process-Priorities-in-Windows-Task-Manager>



(Sent from my laptop.)

__________________________
Simson L. Garfinkel
https://simson.net/
202-649-0029

**Comment by markuskramerIgitt** [comment]
Thank you.
When I lower the priority, disk usage still goes up to 100%
I believe that task manager priority only affects the task scheduler, and
hashdeep needs little CPU in comparison to disk.

I will simply accept that the disk is fully utilized.

**Comment by simsong** [comment]
I think that you may wish to take a course in operating system theory. The OS would rather do something with the drive than nothing; but if you run other tasks, they will be prioritized.

**Comment by markuskramerIgitt** [comment]
I am aware of what an OS does, and actually lowering the priority was a
(acceptable) waste of time.


What wanted is to limit the disk usage.
I may open a feature request.

**Comment by ethus3h** [comment]
I think cgroups can do disk I/O throttling in Linux... maybe there would be some way to use that on Windows (through a VM, or something)?

The other answers here seem irrelevant.

**Comment by simsong** [comment]
There is no evidence that I/O throttling is needed.  I/O throttling is only necessary if there are other applications that are suffering degraded performance because of the I/O activity. The poster does not have any test case of applications that are degraded because of the operation of hashdeep.  The poster is concerned about a hypothetical problem. If the poster has an actual case in which performance is impacted, and that can be replicated, then the poster may be in a position to propose a solution. Otherwise, one is engineering against a hypothetical, unknowable problem.

**Comment by markuskramerIgitt** [comment]
@simsong, I have the impression you do not read my messages:
 - I solved my degredation problem with `-j 1`
 - I have a need to intentionally and optionally trottle disk activity.

I also have the impression that you are lecturing me and you are unwilling to discuss features.

**Comment by simsong** [comment]
Hi Markus,

I read your messages.  I apologize for suggesting that you take a course in operating system theory. 

I disagree that you have the need for a user-level control for throttling disk activity. You say that the system remains responsive and that you are worried about a hypothetical situation that you haven't experienced. Since you have also written that you do not care about performance of hashdeep, I think that you've underspecified the problem that you are trying to solve. 

However, if you wish to write a patch for hashdeep that implements user-level throttling, I'm sure that Jesse K will be happy to review it

Simson
